AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Sample Template for CFN Init
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

  MyS3BucketName:
    Description: Name of an existing bucket to download files from
    Type: String

  ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

  SubnetId:
    Type: AWS::EC2::Subnet::Id

  VpcId:
    Type: AWS::EC2::VPC::Id

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Enable HTTP access via port 80 and SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Ref SSHLocation

  WebServerHost:
    Type: AWS::EC2::Instance
    Metadata:
      Comment: Install a simple PHP application
      # Using CloudFormation Init to make complex ec2 scripts more user readable and easier to deploy
      # CloudFormation launches the Instance and then the instnace calls cfn-init to pull the init data from CloudFormation. Logs go to `/var/log/cfn-init.log`
      # After cfn-init we run cfn-signal to tell CloudFormation whether or not the cfn-init script completed or failed.
      AWS::CloudFormation::Init:
        config:

          # Install Required Packages
          packages:
            yum:
              # Install latest version of "httpd" and "php"
              httpd: []
              php: []

          # Create the required groups
          groups:
            # Creates the "apache" group with a random GID
            apache: {}
            # Creates the group "group2" with the GID 45
            group2:
              gid: "45"

          # Create the required Users
          users:
            # Creates the "apache" user in the group "apache"
            apache:
              groups:
                - apache
            # Create the "user2" user with the UID 50 in the group "group2"
            user2:
              # Attach the user to the group "group2"
              groups:
                - group2
              # Set the UID of the user
              uid: "50"
              # Set the Home Directory of the user
              homeDir: "/custom/home/dir"

          # Download an archive and unpack into the directory (Supports: tar, tar+gz, tar+bz2, zip)
          sources:
            # In the directory "/home/ec2-user/aws-cli" download and unpack the information from "https://github.com/aws/aws-cli/tarball/master"
            "/home/ec2-user/aws-cli": "https://github.com/aws/aws-cli/tarball/master"

          # You can write files to put into the EC2 instance inline or pull them from a URL or even a S3 Bucket
          files:
            "/tmp/cwlogs/apacheaccess.conf":
              # We can use !Sub here to substitute values from CloudFormation into the file! Make sure the format is ${value}
              content: !Sub |
                [general]
                state_file= /var/awslogs/agent-state
                [/var/log/httpd/access_log]
                file = /var/log/httpd/access_log
                log_group_name = ${AWS::StackName}
                log_stream_name = {instance_id}/apache.log
                datetime_format = %d/%b/%Y:%H:%M:%S
              mode: '000400'
              owner: apache
              group: apache
            "/var/www/html/index.php":
              content: !Sub |
                <?php
                echo '<h1>AWS CloudFormation sample PHP application for ${AWS::StackName}</h1>';
                ?>
              mode: '000644'
              owner: apache
              group: apache
            # Setting up cfn-hup ()
            "/etc/cfn/cfn-hup.conf":
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
              mode: "000400"
              owner: "root"
              group: "root"
            "/etc/cfn/hooks.d/cfn-auto-reloader.conf":
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.WebServerHost.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource WebServerHost --region ${AWS::Region}
              mode: "000400"
              owner: "root"
              group: "root"
            # Fetch a webpage from a private S3 bucket
            "/var/www/html/webpage.html":
              # Using the "!Sub" function will substitute anything starting with "${" with the applicable Parameters, References, or Pseudo-variables
              source: !Sub "https://${MyS3BucketName}.s3.${AWS::Region}.amazonaws.com/webpage.html"
              # Setting the file permissions
              mode: '000644'
              # Setting the file owner/group
              owner: apache
              group: apache
              # Specifying the IAM role for pulling the file
              authentication: S3AccessCreds

          # Runs commands, 1 at a time, in alphabetical order. Ran after the file section
          # You could use this with Files to execute a script of commands. Only use if you can't do this with files, groups, users, or packages.
          commands:
            test:
              # Running a command (uses Environment Variables)
              command: "echo \"$MAGIC\" > test.txt"
              # Setting Environment Variables for the execution
              env:
                MAGIC: "I come from the environment!"
              # Setting the Current Working Directory
              cwd: "~"
              # Testing to see if the file exists
              test: test ! -e ~/test.txt

          # Launch Services after the EC2 instance is launched using sysvinit 
          services:
            sysvinit:
              # Enable and Run a Service
              httpd:
                enabled: 'true'
                ensureRunning: 'true'
              # Stop and Disable a service
              postfix:
                enabled: 'false'
                ensureRunning: 'false'
              cfn-hup:
                enable: 'true'
                ensureRunning: 'true'
                # This section checks to see if the files are updated, if they are this restarts the service
                files:
                  - "/etc/cfn/cfn-hup.conf"
                  - "/etc/cfn/hooks.d/cfn-auto-reloader.conf"

      # Setting an IAM role for the EC2 instance
      AWS::CloudFormation::Authentication:
        # Define S3 access credentials
        S3AccessCreds:
          type: S3
          buckets:
            - !Sub ${MyS3BucketName}
          roleName: !Ref InstanceRole
    # This is where we define how CloudFormation should wait for the cfn-init to complete
    CreationPolicy:
      ResourceSignal:
        # Set the timeout of cfn-init to 15 minutes
        Timeout: PT15M
        
    Properties:
      ImageId: !Ref ImageId
      KeyName: !Ref KeyName
      InstanceType: t2.micro
      SubnetId: !Ref SubnetId
      IamInstanceProfile: !Ref InstanceProfile # Reference Instance Profile
      SecurityGroups:
      - !Ref WebServerSecurityGroup
      # We are passing some user data to run the cfn-init and cfn-signal command
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            
            # Get the latest CloudFormation helper scripts
            yum install -y aws-cfn-bootstrap
            
            # Start cfn-init
            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource WebServerHost --region ${AWS::Region}
            
            # cfn-init completed so signal success or not
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource WebServerHost --region ${AWS::Region}
          
  # Creating an IAM role to allow the EC2 application to pull objects from a Bucket
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Principal:
              Service: ec2.amazonaws.com
            Effect: Allow
            Sid: ''
      Policies:
        - PolicyName: AuthenticatedS3GetObjects
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - 's3:GetObject'
                Resource: !Sub 'arn:aws:s3:::${MyS3BucketName}/*'
                Effect: Allow

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref InstanceRole

Outputs:
  InstanceId:
    Description: The instance ID of the web server
    Value:
      !Ref WebServerHost
  WebsiteURL:
    Value:
      !Sub 'http://${WebServerHost.PublicDnsName}'
    Description: URL for newly created LAMP stack
  PublicIP:
    Description: Public IP address of the web server
    Value:
      !GetAtt WebServerHost.PublicIp
